### ISSUE TITLE
How do not close window when click on a button?

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#10]
I trying to use string simpledialog and when I click Ok button, I use a function to validate data-string and reopen window if data-string is not a number.

The Ok callback function run ok, but dialog don't reopen. I don't receive any javascript error.

How can I manually close dialog or prevent dialog to close if I found a error in data-string?

Thank you and sorry any english mistake.

My code:
- start from solicitaPreco function.
- If I put a alert on solicitaPreco before simpledialog call, it show ok if I click Ok button
  
  var solicitaPreco = function () {
      $(this).simpledialog({
          'mode': 'string',
          'prompt': 'How much?',
          'useDialogForceFalse': true,
          'buttons': {
              'Ok': {
                  click: checaPrecoInformado
              },
              'Cancel': {
                  click: function() { }
              }
          }
      });
  }
  
  var checaPrecoInformado = function () {
      var fltPreco = $(self).attr('data-string');
      fltPreco = fltPreco.replace(',', '.');
  
  ```
  if (isNaN(fltPreco)) {
      alert('Invalid value.');
      solicitaPreco();
  } else {
      fltPreco = Math.floor(fltPreco * 100) / 100
      alert('Price: ' + fltPreco);
  }
  ```
  
  }

**Comment by asgeo1** [comment]
I'm having the same problem. There is no way to prevent the dialog from closing, because it always calls .close() after the button click event is executed. You can't change that behaviour currently.

So I'm currently using this workaround:

Change this:

```
props.click.apply(self.element[0], arguments);
self.close();
```

to this:

```
var val = props.click.apply(self.element[0], arguments);
if(val !== false)
    self.close();
```

Then if I don't want the button click event to automatically close the dialog I just have it return false. Returning undefined or true leaves the default behaviour (closing the dialog)
