### ISSUE TITLE
Raw HTML Dialog Opens and Closes

### ISSUE THREAD

**Issue by abernardobr** [jtsage/jquery-mobile-simpledialog#13]
I am accessing the demo site on my iPad and iPhone:

http://dev.jtsage.com/#/jQM-SimpleDialog/demos/blank.html

On the iPad it open the DialogBox and closes, on the iPhone it opens but it is not well formatted and also does not have the same behavior as the iPad.

Is this a normal behavior?

I got the latest files from the github.

Tks,

Augusto

**Comment by abernardobr** [comment]
Copied the example code with the latest jQueryMobile.

Made the follwing changes:

added the parameter useModal: true and changed from vclick to just click.

$('#infoDialogId').live('click', function() {
        $(this).simpledialog({
            'mode' : 'blank',
            'useModal' : true,
            'prompt': false,
            'forceInput': false,
            'fullHTML' :
                    "<ul data-role='listview'><li>Some</li><li>List</li><li>Items</li></ul><a data-role='button' href='#' id='infoDialogCloseId'>Close</a>"
        })
    });

```
$('#infoDialogCloseId').live('click', function() {
    $('#infoDialogId').simpledialog('close');
});
```

on the iPad, works just fine, on the iPhone, it shows like a normal page, w/o the transparent wallpaper on the back like on the iPad, and the close button does not go the the correct place.

**Comment by julianomoraes** [comment]
Hey,

I think that this issue is not fixed.
Firstly thanks for your plugin, it is being very useful for a mobile project that I am working. 
I am using the same code for iphone and ipad apps, it is working fine in the ipad, although is is not well formatted in the iphone.

I did an investigation about this issue and I was able to fix it changing the line 131: If ( docWinWidth > 400
I think that the problem is iphone has a width lower than 400. So, I removed this condition and the dialog worked well in both iphone and ipad.

Thanks,
Juliano

**Comment by jtsage** [comment]
It's a dialog problem then - not surpising.  I do have a possible idea for this, but I need to check on some things (long explanation made short, I don't really like jQM's dialog methods - they are often unpredictable).  At any rate, you can acheive the same thing as removing that line by setting:

useDialogForceFalse: true
