### ISSUE TITLE
Dialog mode doesn't close

### ISSUE THREAD

**Issue by tadas-subonis** [jtsage/jquery-mobile-simpledialog#37]
When in dialog mode (useDialog: true), dialog doesn't close on chrome and safari.

something is off on 178 - 191 lines...

**Comment by jtsage** [comment]
useDialog shouldn't be set by the end user - if you are doing this, try useDialogForceTrue: true, and see if it works better this way - otherwise, I will take a look.  (I actually hate the dialog mode with a passion - it's such a hack to get it to work, and as you noticed, every little change upstream breaks it again)

**Comment by miha2910** [comment]
Hello I have the same problem only I don't use useDialog...but a simple jquery dialog, can someone help me?
