### ISSUE TITLE
Dynamic HTML update doesn't work as documented

### ISSUE THREAD

**Issue by sketchee** [jtsage/jquery-mobile-simpledialog#39]
The documentation mentions that you can dynamically update the full HTML property.  This did not work:

$('#simpleraw').data('simpledialog').options.fullHTML

It gives the error: Uncaught TypeError: Cannot read property 'options' of undefined

**Comment by jtsage** [comment]
Can you post a link to your issue, or dump the relevant details on jsfiddle?  Please check your initial selector too - a lot of issues stem from not getting the right one. (#simpleraw for example)

**Comment by bmcharek** [comment]
HI, I have the same issue. It also gives me a TypeError. Shouldn't data.
So I took your blank.html file and added a log:
    <script>   console.log($('#simpleraw').data('simpledialog').options.fullHTML);</script>
While it recognizes #simpleraw, the error persist in the log. Any help please.
A wild guess (Iam pretty new at this), isn't data expecting 2 arguments?

**Comment by jtsage** [comment]
Well, it is not working on the demo because 'cleanOnClose' is on - or rather, it only works if you check it on the console _while_ the dialog is open.  The purpose of cleanOnClose is to provide single-use dialogs - or, baring that, allow you to open a dialog on the same selector again and again - just re-create it same as you did the first time.

fwiw, this is better explained in the new version SimpleDialog2, which in my opinion is a huge improvement overall.

http://dev.jtsage.com/jQM-SimpleDialog/demos2/

**Comment by bmcharek** [comment]
Sorry for the spam, but just as a suggestion it would be nice to keep the default date in the datepicker.
